CREATE SCHEMA IF NOT EXISTS BLOG;

CREATE TABLE IF NOT EXISTS BLOG.CATEGORY
(
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BLOG.SEQ_CATEGORY MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BLOG.POST
(
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(200) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BLOG.SEQ_POST MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BLOG.POST_CATEGORIESX
(
    POST_IDX NUMBER(11),
    CATEGORIES_IDX NUMBER(11)
);